In [5]:
import pandas as pd
import numpy as np
import os

In [6]:
##getting current dir

current = os.getcwd()
current

'C:\\Users\\chrs-164-ip\\Desktop\\Projects\\SDDP\\General structure\\For github'

In [7]:
##importing user data

user_data=pd.read_csv('input/user_data.csv')
n_stages=user_data.iloc[0,1]
user_data

                                           variables  values
0                                   Number of stages      21
1                          month for initial storage       3
2                            day for initial storage      31
3  nuber of rows from begening of USACE forecsat ...       3
4   nuber of rows from End of USACE forecsat to drop       0
5                              number of small trees       7

In [8]:
cascade_df=pd.read_excel('input/Cascade_info.xlsx',sheet_name='Cascade')
dam_name=cascade_df['name']
dam_name=sorted(dam_name)
dam_name

['BB', 'FP', 'FR', 'GA', 'GP', 'OH']

In [9]:
##definnig input path and file names

path='output/node_solutions/main_tree/'
names=['total_pflow','storage','spill','release']

In [11]:
##loading main tree

main_tree_path=os.path.join(current,'input','Tree.xlsx')
main_tree=pd.read_excel(main_tree_path)

In [12]:
col_name=[]
for dam in dam_name:
    temp_name=dam+'_in'
    col_name.append(temp_name)
col_name=sorted(col_name)
col_name

['BB_in', 'FP_in', 'FR_in', 'GA_in', 'GP_in', 'OH_in']

In [14]:
names

['total_pflow', 'storage', 'spill', 'release']

In [15]:
col_name

['BB_in', 'FP_in', 'FR_in', 'GA_in', 'GP_in', 'OH_in']

In [16]:
##making the solution trees

df_list=[]
co=['Node', 'Parent','Prob' ,'Stage','probability']
for n in names:
    file_p=os.path.join(current,path,"Nodes_"+n+'_solution_clean.csv')
    temp=pd.read_csv(file_p)
    if len(temp.columns)==len(dam_name)*2:
        temp.drop(columns=col_name,inplace=True)
    temp2=pd.concat([temp,main_tree[co]],axis=1)
    df_list.append(temp2)

In [17]:
##checking on of them

df_list[1]

,BB_out,FP_out,FR_out,GA_out,GP_out,OH_out,Node,Parent,Prob,Stage,probability
0,1.631000,15.189553,3.224941,18.211265,0.371439,18.840715,1,0,1.000000,1,1.00
1,1.631000,15.155239,3.261763,18.263544,0.374000,18.806475,2,1,0.680000,2,0.68
2,1.631000,15.163173,3.261340,18.285362,0.374000,18.808227,3,1,0.320000,2,0.32
3,1.631000,15.108189,3.282893,18.310707,0.374000,18.806257,4,2,0.647059,3,0.44
4,1.664130,15.106205,3.273202,18.339708,0.374000,18.764270,5,2,0.352941,3,0.24
...,...,...,...,...,...,...,...,...,...,...,...
311,1.711673,14.183925,4.133436,18.702846,0.374000,18.691244,312,280,0.200000,21,0.02
312,1.631000,14.405975,3.838162,19.356462,0.374000,19.515033,313,283,0.666667,21,0.04
313,1.631000,14.378206,3.685817,19.661501,0.374000,19.426228,314,284,1.000000,21,0.02
314,1.631000,14.955405,3.693327,20.430426,0.374000,19.315516,315,285,1.000000,21,0.02
315,1.631000,14.538921,3.896365,19.965352,0.373021,20.014986,316,286,1.000000,21,0.02

In [18]:
##exporting solution trees

o_path="output/solution_tree/"
h=0
for tree in df_list:
    name_t="solution_tree_"+names[h]
    save_t=os.path.join(current,o_path,name_t+'.csv')
    tree.to_csv(save_t)
    h+=1
    print(save_t)

C:\Users\chrs-164-ip\Desktop\Projects\SDDP\General structure\For github\output/solution_tree/solution_tree_total_pflow.csv
C:\Users\chrs-164-ip\Desktop\Projects\SDDP\General structure\For github\output/solution_tree/solution_tree_storage.csv
C:\Users\chrs-164-ip\Desktop\Projects\SDDP\General structure\For github\output/solution_tree/solution_tree_spill.csv
C:\Users\chrs-164-ip\Desktop\Projects\SDDP\General structure\For github\output/solution_tree/solution_tree_release.csv

In [19]:
df_list[1]

,BB_out,FP_out,FR_out,GA_out,GP_out,OH_out,Node,Parent,Prob,Stage,probability
0,1.631000,15.189553,3.224941,18.211265,0.371439,18.840715,1,0,1.000000,1,1.00
1,1.631000,15.155239,3.261763,18.263544,0.374000,18.806475,2,1,0.680000,2,0.68
2,1.631000,15.163173,3.261340,18.285362,0.374000,18.808227,3,1,0.320000,2,0.32
3,1.631000,15.108189,3.282893,18.310707,0.374000,18.806257,4,2,0.647059,3,0.44
4,1.664130,15.106205,3.273202,18.339708,0.374000,18.764270,5,2,0.352941,3,0.24
...,...,...,...,...,...,...,...,...,...,...,...
311,1.711673,14.183925,4.133436,18.702846,0.374000,18.691244,312,280,0.200000,21,0.02
312,1.631000,14.405975,3.838162,19.356462,0.374000,19.515033,313,283,0.666667,21,0.04
313,1.631000,14.378206,3.685817,19.661501,0.374000,19.426228,314,284,1.000000,21,0.02
314,1.631000,14.955405,3.693327,20.430426,0.374000,19.315516,315,285,1.000000,21,0.02
315,1.631000,14.538921,3.896365,19.965352,0.373021,20.014986,316,286,1.000000,21,0.02

In [20]:
full_list=[]
for solution in df_list:
    solution_list=[]
    for i in range(len(dam_name)):
        leaf=solution.loc[temp2['Stage']==n_stages].iloc[:,i]
        tmp=pd.DataFrame(index=range(n_stages),columns=range(len(leaf)))
        tmp.iloc[n_stages-1,:]=leaf
        parents=temp2.iloc[leaf.index,-4]
        for node in range(n_stages-2,-1,-1):
            tmp.iloc[node,:]=solution.iloc[parents-1,i]
            parents=temp2.iloc[parents-1,-4]
        solution_list.append(tmp)
    full_list.append(solution_list)

In [21]:
o_path="output/solution_scenarios/"
s_name=['total_pflow','storage','spill','release']
d_name=sorted(dam_name)
s=0
for solution in full_list:
    d=0
    for dam in solution:
        name=d_name[d]+"_solution_scenarios_"+s_name[s]+'.csv'
#         print(name)
        save_p=os.path.join(current,o_path,name)
        print(save_p)
        dam.to_csv(save_p,index=False,header=False)
        d+=1
    s+=1

C:\Users\chrs-164-ip\Desktop\Projects\SDDP\General structure\For github\output/solution_scenarios/BB_solution_scenarios_total_pflow.csv
C:\Users\chrs-164-ip\Desktop\Projects\SDDP\General structure\For github\output/solution_scenarios/FP_solution_scenarios_total_pflow.csv
C:\Users\chrs-164-ip\Desktop\Projects\SDDP\General structure\For github\output/solution_scenarios/FR_solution_scenarios_total_pflow.csv
C:\Users\chrs-164-ip\Desktop\Projects\SDDP\General structure\For github\output/solution_scenarios/GA_solution_scenarios_total_pflow.csv
C:\Users\chrs-164-ip\Desktop\Projects\SDDP\General structure\For github\output/solution_scenarios/GP_solution_scenarios_total_pflow.csv
C:\Users\chrs-164-ip\Desktop\Projects\SDDP\General structure\For github\output/solution_scenarios/OH_solution_scenarios_total_pflow.csv
C:\Users\chrs-164-ip\Desktop\Projects\SDDP\General structure\For github\output/solution_scenarios/BB_solution_scenarios_storage.csv
C:\Users\chrs-164-ip\Desktop\Projects\SDDP\General structure\For github\output/solution_scenarios/FP_solution_scenarios_storage.csv
C:\Users\chrs-164-ip\Desktop\Projects\SDDP\General structure\For github\output/solution_scenarios/FR_solution_scenarios_storage.csv
C:\Users\chrs-164-ip\Desktop\Projects\SDDP\General structure\For github\output/solution_scenarios/GA_solution_scenarios_storage.csv
C:\Users\chrs-164-ip\Desktop\Projects\SDDP\General structure\For github\output/solution_scenarios/GP_solution_scenarios_storage.csv
C:\Users\chrs-164-ip\Desktop\Projects\SDDP\General structure\For github\output/solution_scenarios/OH_solution_scenarios_storage.csv
C:\Users\chrs-164-ip\Desktop\Projects\SDDP\General structure\For github\output/solution_scenarios/BB_solution_scenarios_spill.csv
C:\Users\chrs-164-ip\Desktop\Projects\SDDP\General structure\For github\output/solution_scenarios/FP_solution_scenarios_spill.csv
C:\Users\chrs-164-ip\Desktop\Projects\SDDP\General structure\For github\output/solution_scenarios/FR_solution_scenarios_spill.csv
C:\Users\chrs-164-ip\Desktop\Projects\SDDP\General structure\For github\output/solution_scenarios/GA_solution_scenarios_spill.csv
C:\Users\chrs-164-ip\Desktop\Projects\SDDP\General structure\For github\output/solution_scenarios/GP_solution_scenarios_spill.csv
C:\Users\chrs-164-ip\Desktop\Projects\SDDP\General structure\For github\output/solution_scenarios/OH_solution_scenarios_spill.csv
C:\Users\chrs-164-ip\Desktop\Projects\SDDP\General structure\For github\output/solution_scenarios/BB_solution_scenarios_release.csv
C:\Users\chrs-164-ip\Desktop\Projects\SDDP\General structure\For github\output/solution_scenarios/FP_solution_scenarios_release.csv
C:\Users\chrs-164-ip\Desktop\Projects\SDDP\General structure\For github\output/solution_scenarios/FR_solution_scenarios_release.csv
C:\Users\chrs-164-ip\Desktop\Projects\SDDP\General structure\For github\output/solution_scenarios/GA_solution_scenarios_release.csv
C:\Users\chrs-164-ip\Desktop\Projects\SDDP\General structure\For github\output/solution_scenarios/GP_solution_scenarios_release.csv
C:\Users\chrs-164-ip\Desktop\Projects\SDDP\General structure\For github\output/solution_scenarios/OH_solution_scenarios_release.csv

In [22]:
print('code in Done!')

code in Done!